import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:meta/meta.dart';

import '../../../models/arabic_languague_education_model.dart';

part 'education_state.dart';

class EducationCubit extends Cubit<EducationState> {
  EducationCubit() : super(EducationInitial());

  static EducationCubit get(context) => BlocProvider.of(context);

  List<ArabicLettersModel> arabicLettersModel = [
    ArabicLettersModel(
        'حرف الالف (أ)',
        '0:02',
        'لغه الاشاره بالعربيه',
        'حرف الألف في الأبجدية العربية هو أول حرف وأول حرف متحرك في الأبجدية، ويُمثل بالرمز "أ".',
        'assets/images/quizLettersImages/01.png',
        'render/01.mp4',false),
    ArabicLettersModel(
        'حرف الباء (ب)',
        '0:50',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'render/02.mp4',false),
    ArabicLettersModel(
        'حرف التاء (ت)',
        '0:43',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/k8DXozUtsDI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAgI_rLzZpzFi4LZ-t_QtgVuCE7dw',
        'render/03.mp4',false),
    ArabicLettersModel(
        'حرف الثاء (ث)',
        '1:01',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/IaJRTJbOpyM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCLOCdZsoOYjiCWzNQa2cf4ghkOHw',
        'render/04.mp4',false),
    ArabicLettersModel(
        'حرف الجيم (ج)',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/eCY8bHakcAs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCo8lpM_iflkg7kGDe-93RPZqiN1w',
        'render/05.mp4',false),
    ArabicLettersModel(
        'حرف الحاء (ح)',
        '0:55',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/bFJxp3zvN0E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCCMjRGgEl37FITfDKMGkWBD1xhfA',
        'render/07.mp4',false),
    ArabicLettersModel(
        'حرف الخاء (خ)',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/tRR0-2hD53E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAAlh1wxw3ZJxVPOoQOvMzJ2Vu0xA',
        'render/08.mp4',false),
    ArabicLettersModel(
        'حرف الدال (د)',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/adW4lsYm1hc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWKndOoC2IR6IeaBEY2skBSNioOA',
        'render/09.mp4',false),
    ArabicLettersModel(
        'حرف الذال (ذ)',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/g84TS0NXuIo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDQvStD758_UgqD38eLbWKEiyRsTg',
        'render/10.mp4',false),
    ArabicLettersModel(
        'حرف الراء (ر)',
        '0:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/L7lXHvKuKds/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCH1CDASJfdpfX07BJNxTpR_7aVdw',
        'render/11.mp4',false),
    ArabicLettersModel(
        'حرف الزال (ز)',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/vNYlOCJQZbo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB7dzgxqePBRwQi7SlJrWI4QgEV0A',
        'render/12.mp4',false),
    ArabicLettersModel(
        'حرف السين (س)',
        '1:17',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/JtVf-jaf4ko/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA_WrdxNgHOLPFLa7suKPSzYOGqsA',
        'render/13.mp4',false),
    ArabicLettersModel(
        'حرف الشين (ش)',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/fZHh6eFF8Lg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC7-SBUccsCBxRR7OwHMHX38VV1GA',
        'render/14.mp4',false),
    ArabicLettersModel(
        'حرف الصاد (ص)',
        '0:53',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/YtAGzLPEfxI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCAMLjAc3C_xt8B1iqtHpcNCO8YAA',
        'render/15.mp4',false),
    ArabicLettersModel(
        'حرف الضاد (ض)',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'render/15.mp4',false),
    ArabicLettersModel(
        'حرف الطاء (ط)',
        '1:09',
        'لغه الاشاره بالعربيه',
        '',
        'https://i.ytimg.com/vi/AJeEBx3sbEc/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYAC0AWKAgwIABABGGUgWChBMA8=&rs=AOn4CLB_FpExm4mpOuZvZ--aj4-QfHCiOg',
        'render/16.mp4',false),
    ArabicLettersModel(
        'حرف الظاء (ظ)',
        '0:50',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'render/17.mp4',false),
    ArabicLettersModel(
        'حرف العين (ع)',
        '0:50',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'render/18.mp4',false),
    ArabicLettersModel(
        'حرف الغين (غ)',
        '0:50',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'render/19.mp4',false),
    ArabicLettersModel(
        'حرف الفاء (ف)',
        '0:43',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/k8DXozUtsDI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAgI_rLzZpzFi4LZ-t_QtgVuCE7dw',
        'render/20.mp4',false),
    ArabicLettersModel(
        'حرف القاف (ق)',
        '1:01',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/IaJRTJbOpyM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCLOCdZsoOYjiCWzNQa2cf4ghkOHw',
        'render/21.mp4',false),
    ArabicLettersModel(
        'حرف الكاف (ك)',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/eCY8bHakcAs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCo8lpM_iflkg7kGDe-93RPZqiN1w',
        'render/22.mp4',false),
    ArabicLettersModel(
        'حرف اللام (ل)',
        '0:55',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/bFJxp3zvN0E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCCMjRGgEl37FITfDKMGkWBD1xhfA',
        'render/23.mp4',false),
    ArabicLettersModel(
        'حرف الميم (م)',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/tRR0-2hD53E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAAlh1wxw3ZJxVPOoQOvMzJ2Vu0xA',
        'render/24.mp4',false),
    ArabicLettersModel(
        'حرف النون (ن)',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/tRR0-2hD53E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAAlh1wxw3ZJxVPOoQOvMzJ2Vu0xA',
        'render/25.mp4',false),
    ArabicLettersModel(
        'حرف الهاء (ه)',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/adW4lsYm1hc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWKndOoC2IR6IeaBEY2skBSNioOA',
        'render/26.mp4',false),
    ArabicLettersModel(
        'حرف الواو (و)',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/g84TS0NXuIo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDQvStD758_UgqD38eLbWKEiyRsTg',
        'render/27.mp4',false),
    ArabicLettersModel(
        'حرف الياء (ي)',
        '0:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/L7lXHvKuKds/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCH1CDASJfdpfX07BJNxTpR_7aVdw',
        'render/28.mp4',false),

  ];

  List<ArabicNumbersModel> arabicNumbersModel = [
    ArabicNumbersModel(
        'رقم 1 | Number 1',
        '0:50',
        'لغه الاشاره بالعربيه',
        'رقم 1 هو العدد الأول في النظام العددي الطبيعي. يأتي بعد الصفر وقبل الرقم 2. في العديد من الثقافات، يُعتبر الرقم 1 رمزًا للبداية والوحدة، ويستخدم في العديد من السياقات للتعبير عن الوحدة والتمييز بين الأشياء.',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'render/numbers/1.mp4',false),
    ArabicNumbersModel(
        'رقم 2 | Number 2',
        '0:43',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/k8DXozUtsDI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAgI_rLzZpzFi4LZ-t_QtgVuCE7dw',
        'render/numbers/2.mp4',false),
    ArabicNumbersModel(
        'رقم 3 | Number 3',
        '1:01',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/IaJRTJbOpyM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCLOCdZsoOYjiCWzNQa2cf4ghkOHw',
        'render/numbers/3.mp4',false),
    ArabicNumbersModel(
        'رقم 4 | Number 4',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/eCY8bHakcAs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCo8lpM_iflkg7kGDe-93RPZqiN1w',
        'render/numbers/4.mp4',false),
    ArabicNumbersModel(
        'رقم 5 | Number 5',
        '0:55',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/bFJxp3zvN0E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCCMjRGgEl37FITfDKMGkWBD1xhfA',
        'render/numbers/5.mp4',false),
    ArabicNumbersModel(
        'رقم 6 | Number 6',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/tRR0-2hD53E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAAlh1wxw3ZJxVPOoQOvMzJ2Vu0xA',
        'render/numbers/6.mp4',false),
    ArabicNumbersModel(
        'رقم 7 | Number 7',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/adW4lsYm1hc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWKndOoC2IR6IeaBEY2skBSNioOA',
        'render/numbers/7.mp4',false),
    ArabicNumbersModel(
        'رقم 8 | Number 8',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/g84TS0NXuIo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDQvStD758_UgqD38eLbWKEiyRsTg',
        'render/numbers/8.mp4',false),
    ArabicNumbersModel(
        'رقم 9 | Number 9',
        '0:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/L7lXHvKuKds/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCH1CDASJfdpfX07BJNxTpR_7aVdw',
        'render/numbers/9.mp4',false),
    ArabicNumbersModel(
        'رقم 10 | Number 10',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/vNYlOCJQZbo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB7dzgxqePBRwQi7SlJrWI4QgEV0A',
        'render/numbers/10.mp4',false),
    ArabicNumbersModel(
        'رقم 11 | Number 11',
        '1:17',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/JtVf-jaf4ko/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA_WrdxNgHOLPFLa7suKPSzYOGqsA',
        'https://youtu.be/JtVf-jaf4ko?si=MrPe_BseMnvZX8zv',false),
    ArabicNumbersModel(
        'رقم 12 | Number 12',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/fZHh6eFF8Lg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC7-SBUccsCBxRR7OwHMHX38VV1GA',
        'https://youtu.be/fZHh6eFF8Lg?si=7u3pGMv4PCGH61fI',false),
    ArabicNumbersModel(
        'رقم 13 | Number 13',
        '0:53',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/YtAGzLPEfxI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCAMLjAc3C_xt8B1iqtHpcNCO8YAA',
        'https://youtu.be/YtAGzLPEfxI?si=b_gdxoEWHuzVwvMe',false),
    ArabicNumbersModel(
        'رقم 14 | Number 14',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 15 | Number 15',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 16 | Number 16',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 17 | Number 17',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 18 | Number 18',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 19 | Number 19',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
    ArabicNumbersModel(
        'رقم 20 | Number 20',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),

  ];

  List<ArabicLettersModel> arabicWordsModel = [
    ArabicLettersModel(
        'الحروف الابجدية بلغة الاشاره العربيه | The letters in لغه الاشاره بالعربيه',
        '1:09',
        'لغه الاشاره بالعربيه',
        '',
        'https://i.ytimg.com/vi/AJeEBx3sbEc/hqdefault.jpg?sqp=-oaymwE1CKgBEF5IVfKriqkDKAgBFQAAiEIYAXABwAEG8AEB-AH-CYAC0AWKAgwIABABGGUgWChBMA8=&rs=AOn4CLB_FpExm4mpOuZvZ--aj4-QfHCiOg',
        'https://youtu.be/AJeEBx3sbEc?si=uG5D-QjIZxhI_pOb',false),
    ArabicLettersModel(
        'الاحساس بلغة الاشاره العربيه | The feeling is in لغه الاشاره بالعربيه',
        '0:50',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/pngr7NcWyOw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQdN4nsSYTNIccGgElIyO9zEzLAQ',
        'https://youtu.be/pngr7NcWyOw?si=0SvXhPjHdnmxs7rt',false),
    ArabicLettersModel(
        'الاعداد بلغه الاشاره العربيه | The numbers are in لغه الاشاره بالعربيه',
        '0:43',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/k8DXozUtsDI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAgI_rLzZpzFi4LZ-t_QtgVuCE7dw',
        'https://youtu.be/k8DXozUtsDI?si=mtgygUuHl23xARAj',false),
    ArabicLettersModel(
        'الالوان بلغه الاشاره العربيه | The colors are in لغه الاشاره بالعربيه',
        '1:01',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/IaJRTJbOpyM/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCLOCdZsoOYjiCWzNQa2cf4ghkOHw',
        'render/0001-0050.mp4',false),
    ArabicLettersModel(
        'الصلاه بلغه الاشاره العربيه | Prayer in لغه الاشاره بالعربيه',
        '0:39',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/eCY8bHakcAs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCo8lpM_iflkg7kGDe-93RPZqiN1w',
        'render/0002-0050.mp4',false),
    ArabicLettersModel(
        'المستشفى بلغه الاشاره العربيه | The hospital is in لغه الاشاره بالعربيه',
        '0:55',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/bFJxp3zvN0E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCCMjRGgEl37FITfDKMGkWBD1xhfA',
        'render/0003-0050.mp4',false),
    ArabicLettersModel(
        'الوجبات السريعه بلغه الاشاره العربيه | Fast food in لغه الاشاره بالعربيه',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/tRR0-2hD53E/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAAlh1wxw3ZJxVPOoQOvMzJ2Vu0xA',
        'https://youtu.be/tRR0-2hD53E?si=WBt8lO6Oorch40bx',false),
    ArabicLettersModel(
        'العملات بلغه الاشاره العربيه | Currencies in لغه الاشاره بالعربيه',
        'لغه الاشاره بالعربيه',
        '0:39',
        'ASL',
        'https://i.ytimg.com/vi/adW4lsYm1hc/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBWKndOoC2IR6IeaBEY2skBSNioOA',
        'https://youtu.be/adW4lsYm1hc?si=ndexQ6GBSeuGQJ51',false),
    ArabicLettersModel(
        'العائله بلغه الاشاره العربيه | The family in لغه الاشاره بالعربيه',
        '1:09',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/g84TS0NXuIo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDQvStD758_UgqD38eLbWKEiyRsTg',
        'https://youtu.be/g84TS0NXuIo?si=nFAU3Go60P6pXWCW',false),
    ArabicLettersModel(
        'المنزل بلغه الاشاره العربيه | The house is in لغه الاشاره بالعربيه',
        '0:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/L7lXHvKuKds/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCH1CDASJfdpfX07BJNxTpR_7aVdw',
        'https://youtu.be/L7lXHvKuKds?si=FKKY8hB3zoyaYI5-',false),
    ArabicLettersModel(
        'الاطعمه بلغه الاشاره العربيه | The foods are in لغه الاشاره بالعربيه',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/vNYlOCJQZbo/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB7dzgxqePBRwQi7SlJrWI4QgEV0A',
        'https://youtu.be/vNYlOCJQZbo?si=oMIzzWIolca5nH0g',false),
    ArabicLettersModel(
        'عرف بنفسك بلغه الاشاره العربيه | Introduce yourself in لغه الاشاره بالعربيه',
        '1:17',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/JtVf-jaf4ko/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA_WrdxNgHOLPFLa7suKPSzYOGqsA',
        'https://youtu.be/JtVf-jaf4ko?si=MrPe_BseMnvZX8zv',false),
    ArabicLettersModel(
        'ايام الاسبوع بلغه الاشاره العربيه | A week in Arabia Sign Language',
        '0:41',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/fZHh6eFF8Lg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC7-SBUccsCBxRR7OwHMHX38VV1GA',
        'https://youtu.be/fZHh6eFF8Lg?si=7u3pGMv4PCGH61fI',false),
    ArabicLettersModel(
        'شوارع المدينه | City Streets',
        '0:53',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/YtAGzLPEfxI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCAMLjAc3C_xt8B1iqtHpcNCO8YAA',
        'https://youtu.be/YtAGzLPEfxI?si=b_gdxoEWHuzVwvMe',false),
    ArabicLettersModel(
        'وسائل النقل الاساسيه بلغه الاشاره العربيه | Basic means of transportation in لغه الاشاره بالعربيه',
        '1:21',
        'لغه الاشاره بالعربيه',
        'ASL',
        'https://i.ytimg.com/vi/w8iPe1wisns/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQ0qG_A0TzUM3Ih-i2nuYVlIaNtQ',
        'https://youtu.be/w8iPe1wisns?si=QPLSucYFNTpMDbpo',false),
  ];

}
